import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { Toaster } from "@/components/ui/sonner"
import {Providers} from "@/providers/providers";
// Hind_Siliguri, Tiro_Bangla
import {Noto_Sans_Bengali} from 'next/font/google'
import "./globals.css";
import {SearchBar} from "@/components/searchbar";


const HindSiliguri = Noto_Sans_Bengali({
    subsets: ['latin', 'bengali'], // Bengali subset for proper rendering
    weight: ['400', '600', '700'], // Add the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
    <body
        className={HindSiliguri.className}
    >

    <Providers>
        <SidebarProvider>
            <AppSidebar/>
            <main className="w-full mx-1 xl:mx-5">
                <div className="w-full sticky top-0 z-20 bg-white py-1 xl:py-3 flex justify-start items-start">
                    <SidebarTrigger className='mt-2 bg-gray-300'/>
                    <SearchBar/>
                </div>


                <div className='mt-6 h-5/6'>
                    {children}
                </div>

            </main>
        </SidebarProvider>

        <Toaster richColors />
    </Providers>

    </body>
    </html>
  );
}
