import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"


import {Hind_Siliguri} from 'next/font/google'
import {Input} from "@/components/ui/input";
import {Button} from "@/components/ui/button";

import "./globals.css";
import {IoSearch} from "react-icons/io5";


const HindSiliguri = Hind_Siliguri({
    subsets: ['latin', 'bengali'], // Bengali subset for proper rendering
    weight: ['400', '600', '700'], // Add the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={HindSiliguri.className}
    >
    <SidebarProvider>
        <AppSidebar/>
        <main className="w-full mx-1 xl:mx-5">
            <div className="w-full sticky top-0 z-20 bg-white py-1 xl:py-3 overflow-hidden flex justify-start items-start">
                <SidebarTrigger className='mt-2 bg-gray-300'/>
                <div className="px-2 xl:px-7 flex justify-end w-full mt-2 xl:mt-1">
                    <div className="flex w-full justify-center max-w-sm items-center space-x-2">
                        <Input type="email" placeholder="খুজুন......"/>
                        <Button type="submit">
                            <IoSearch/>
                        </Button>
                    </div>
                </div>
            </div>


            <div className='mt-6'>
                {children}
            </div>

        </main>
    </SidebarProvider>


    </body>
    </html>
  );
}
