import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"


import {Hind_Siliguri} from 'next/font/google'
import {Input} from "@/components/ui/input";
import {Button} from "@/components/ui/button";

import "./globals.css";
import {IoSearch} from "react-icons/io5";
import Link from "next/link";
import {LuArrowUpRight, LuSearch} from "react-icons/lu";
import {SearchBar} from "@/components/searchbar";


const HindSiliguri = Hind_Siliguri({
    subsets: ['latin', 'bengali'], // Bengali subset for proper rendering
    weight: ['400', '600', '700'], // Add the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
    <body
        className={HindSiliguri.className}
    >
    <SidebarProvider>
        <AppSidebar/>
        <main className="w-full mx-1 xl:mx-5">
            <div className="w-full sticky top-0 z-20 bg-white py-1 xl:py-3 flex justify-start items-start">
                <SidebarTrigger className='mt-2 bg-gray-300'/>
                <SearchBar/>
            </div>


            <div className='mt-6 h-5/6'>
                {children}
            </div>

        </main>
    </SidebarProvider>


    </body>
    </html>
  );
}
